### ISSUE TITLE
Using AutoMapper Normalizer Breaks OpenAPI in API Platform

### ISSUE THREAD

**Issue by TheoD02** [jolicode/automapper#249]
When I enable the `normalizer.enabled` parameter and keep the default `normalizer.priority` set to `1000`, the OpenAPI documentation exposed by API Platform is broken (not tested with NelmioApiDoc yet)

The exported OpenAPI spec looks like this:  

```json
{
  "components": {
    "extensionProperties": []
  },
  "extensionProperties": [],
  "info": {
    "description": "This is a simple API built with API Platform.",
    "extensionProperties": [],
    "title": "Hello API Platform",
    "version": "1.0.0"
  },
  "openapi": "3.1.0",
  "paths": {
    "paths": {
      "/api/articles/{id}": {},
      "/api/articles": {},
      "/api/categories/{id}": {},
      "/api/categories": {}
    }
  },
  "security": [],
  "servers": [
    {}
  ],
  "tags": [
    {},
    {}
  ]
}
```

As you can see, all paths are empty objects, which should not happen.  

Configuration used :
```yaml
automapper:
  class_prefix: "Symfony_Mapper_"
  constructor_strategy: 'auto'
  date_time_format: !php/const DateTimeInterface::RFC3339
  check_attributes: true
  auto_register: true
  map_private_properties: true
  allow_readonly_target_to_populate: false
  normalizer:
    enabled: true
    only_registered_mapping: false
    priority: 1000
  loader:
    eval: false
    cache_dir: "%kernel.cache_dir%/automapper"
    reload_strategy: "always"
  serializer_attributes: true
  api_platform: false
  name_converter: null
  mapping:
    paths:
      - "%kernel.project_dir%/src/Entity"
```

### Expected Behavior  
The OpenAPI documentation should contain full definitions for the paths, not empty objects.  

### Workaround  
Lowering the priority of the AutoMapper normalizer fixes the issue, but this is not an efficient solution because it may prevent the normalizer from being used in cases where it's needed.  

### Question  
Do you have any idea how to properly fix this issue? I'm open to contributing a PR if there's a recommended approach
